name: deploy nextjs app
on:
  push:
    branches:
      - main
jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: cereate .env file
        run: 
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env 

      - name: build docker image
        run: 
          docker build -t nextjs-app .
      - name: docker login
        run: 
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
      - name: push docker image
        run:
          docker push tinu10/nextjs-app
  deploy:
    runs_on: ubuntu-latest
    needs: build
    steps:
      - name: pull docker image
        run: 
          docker pull tinu10/nextjs-app:latest
      - name: delete existing old container
        run: 
          docker rm -f nextjs-app   
      - name: run docker container
        run: 
          docker run -d -p 3000:3000 --name nextjs-app tinu10/nextjs-app:latest